// Code generated by hertz generator.

package zgs_service_discovery

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	zgs_service_discovery "github.com/likenxy/zgs_service_discovery/biz/model/zgs_service_discovery"
)

// Regist .
// @router /regist [POST]
func Regist(ctx context.Context, c *app.RequestContext) {
	var err error
	var req zgs_service_discovery.RegistQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(zgs_service_discovery.RegistResponse)

	c.JSON(200, resp)
}

// ListAgents .
// @router /list_agents [POST]
func ListAgents(ctx context.Context, c *app.RequestContext) {
	var err error
	var req zgs_service_discovery.ListAgentsInfoQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(zgs_service_discovery.ListAgentsInfoResponse)

	c.JSON(200, resp)
}
